PR_DESCRIPTION_TEMPLATE = """
## What does this PR do?
{summary}

## Why was this change made?
{reason}

## Files Changed
{changed_files}

## Diff Summary
{diff_summary}

## Notes
- This PR was automatically generated by RepoMind
- All changes follow existing code style and conventions
- No existing functionality was removed
"""


def build_pr_description(
    summary: str,
    reason: str,
    changed_files: list,
    diff_summary: str,
) -> str:
    """
    Builds a professional PR description using the template above.
    Called by tools/pr_tool.py when opening a Pull Request.
    """
    files_formatted = "\n".join([f"- `{f}`" for f in changed_files])

    return PR_DESCRIPTION_TEMPLATE.format(
        summary=summary or "Automated code changes applied by RepoMind.",
        reason=reason or "Instruction provided by user through HackingTheRepo platform.",
        changed_files=files_formatted or "- No files listed",
        diff_summary=diff_summary or "No diff summary available.",
    )
